### ISSUE TITLE
3.15.0 release tracking

### ISSUE THREAD

**Issue by emillon** [ocaml/dune#10300]
## pre-branch blockers

(none)

## known blockers

- [x] All 3.14 changelogs merged
- [x] test mirage
- [x] test nix-overlays
* [x] #10327
  * [x] backport: #10332 
* [x] #10314
* [x] #10315
* [x] #10336
  * [x] backport: #10337

## alpha1 (2024-03-25)

- [x] release https://github.com/ocaml/opam-repository/pull/25585
- [x] triage
- [x] go/no go

## alpha2 (2024-03-29)

- [x] release https://github.com/ocaml/opam-repository/pull/25605
  - [x] test nix-overlays: https://github.com/nix-ocaml/nix-overlays/pull/1356
- [x] triage
- [x] go/no go

## release

- [x] changelog
- [x] release https://github.com/ocaml/opam-repository/pull/25615
- [x] triage

## post-release

- [X] ocaml.org changelog
  - https://github.com/ocaml/ocaml.org/pull/2316
  - https://ocaml.org/changelog/2024-04-03-dune-3.15.0 once ocaml.org updates
- [X] discuss post
 - https://discuss.ocaml.org/t/ann-dune-3-15/14438
- [X] close milestone
