### ISSUE TITLE
3.15.1 release tracking

### ISSUE THREAD

**Issue by emillon** [ocaml/dune#10427]
## Preparation 
- need backport
  - [x] #10333
  - [x] #10382
  - [x] #10412
  - [x] #10428
- backports
  - [x] #10431
  - [x] #10432
  - [x] #10433
  - [x] #10434
## Release
- [x] prepare
- [x] release https://github.com/ocaml/opam-repository/pull/25690
- [x] triage
## Post-release
- [x] changelog merged in main
- [x] ocaml.org https://github.com/ocaml/ocaml.org/pull/2389
- [x] discuss

**Comment by anmonteiro** [comment]
as reported in https://github.com/ocaml/opam-repository/pull/25690#issuecomment-2063046712, 3.15.1 breaks ocaml-protoc-plugin. 

The offending set of changes seems to be https://github.com/ocaml/dune/pull/10432 / #10382

**Comment by jonahbeckford** [comment]
- [ ] I haven't been able to finish testing out the changes between Dune 3.12.1 and 3.15.0 because of an unrelated block in the latest opam beta. If possible, would be nice if I can finish my DkML distribution testing before 3.15.1 goes out the door; it has a bunch of tests that Dune and Opam CI will not cover. I don't anticipate the opam beta blocker taking more than a day or two to resolve. *I'll comment here when it is done, or just ping me.*

**Comment by emillon** [comment]
So there's indeed a regression on ocaml-protoc-plugin, including the last version. It looks like we were ignoring the cycle before, and now it's causing an issue. I filed #10447 for this but it any case that can't be fixed in a patch release so I'll cut 3.15.2 without it.

@jonahbeckford 3.15.1 has already been tagged, but your input is valuable for 3.15.2 which I'll prepare today. Let me know if you have any feedback about it.

**Comment by emillon** [comment]
(amending what I said above, the fix will be to backport #10442)

**Comment by Leonidas-from-XIV** [comment]
However, given 3.15.1 is not merged, I think we should close that PR and replace it with 3.15.2.

**Comment by emillon** [comment]
yes, I'll do that when the changelog etc have been merged

**Comment by jonahbeckford** [comment]
Thanks. I have long test cycles so I'm stuck testing Dune 3.15.0 for the time being. And since I haven't found any Windows blockers (yet) I'll probably ship DkML 2.1.1 with Dune 3.15.0.

I don't have the resources to increase the cadence, so (in hindsight) it is better just keeping with the status quo.

**Comment by emillon** [comment]
OK, thanks. Note that 3.15.1 includes a fix for gcc 4.8.5.
