### ISSUE TITLE
3.15.2 release tracking

### ISSUE THREAD

**Issue by emillon** [ocaml/dune#10448]
## Preparation 
- need backport
  - [x] #10442
  - [x] #10446
- backports
  - [x] #10449
  - [x] #10450
- [x] feedback from @jonahbeckford 
- [x] nix-overlays CI https://github.com/nix-ocaml/nix-overlays/pull/1412
## Release
- [x] prepare https://github.com/ocaml/dune/pull/10453
- [x] release https://github.com/ocaml/opam-repository/pull/25714
- [x] triage
## Post-release
- [x] update nix-overlays PR
- [x] changelog merged in main
- [x] ocaml.org https://github.com/ocaml/ocaml.org/pull/2389
- [x] discuss
