### ISSUE TITLE
3.15.3 release tracking

### ISSUE THREAD

**Issue by emillon** [ocaml/dune#10566]
## Preparation

- need backport
  - [ ] #10554
  - [ ] #10564
- backports
  - (none)
- [ ] add fixes in #10564 backported entry
- [ ] nix-overlays CI

## Release

- [ ] prepare
- [ ] release
- [ ] triage

## Post-release

- [ ] changelog merged in main
- [ ] ocaml.org
- [ ] discuss
