### ISSUE TITLE
3.16.0 release tracking

### ISSUE THREAD

**Issue by emillon** [ocaml/dune#10611]
## pre-branch blockers

(none)

## known blockers

- [x] All 3.15 changelogs merged
- [x] test mirage
- [x] test nix-overlays https://github.com/nix-ocaml/nix-overlays/pull/1496
- [x] indexing rules situation #10623
- [x] bin-annot-occurences for melange
- [x] add changelog for #10581

## alpha1 (2024-06-05)

- [x] release https://github.com/ocaml/opam-repository/pull/26022
- [x] triage
- [x] go/no go

## alpha2 (2024-06-11)

- [x] release https://github.com/ocaml/opam-repository/pull/26060
- [x] triage
  - [x] melange.4.0.0-52 needs conflict against dune https://github.com/ocaml/opam-repository/pull/26088
- [x] go/no go

## release

- [x] release https://github.com/ocaml/opam-repository/pull/26101
- [x] triage
- [x] update nix-overlays PR

## post-release

- [x] merge changelog https://github.com/ocaml/dune/pull/10663
- [x] ocaml.org changelog https://github.com/ocaml/ocaml.org/pull/2566
- [x] discuss post
- [x] close milestone

**Comment by hannesm** [comment]
From the changes, I couldn't spot an entry for #10581 fixing #10460, maybe worth to mention (as far as I can tell, the 3.16.0~alpha1 contains the fix)? Thanks a lot for your work.

**Comment by emillon** [comment]
good point, we forgot to add one in the PR.
