### ISSUE TITLE
3.16.1 release tracking

### ISSUE THREAD

**Issue by maiste** [ocaml/dune#11050]
## Preparation

- need backport:
  - [x] https://github.com/ocaml/dune/pull/10962 
  - [x] https://github.com/ocaml/dune/pull/11009 
- backport:
  - https://github.com/ocaml/dune/pull/11051 
- restrict pp version `< 2.0` https://github.com/ocaml/dune/pull/11055/commits/c74903764303c1c4220f12c3cf50c0810a162c90

## Release
- [x] prepare https://github.com/ocaml/dune/pull/11055
- [x] release 3.16.1 on opam https://github.com/ocaml/opam-repository/pull/26816
- [x] triage

## Post-release

- [x] upgrade version in nix-overlay? Maybe not needed (https://github.com/nix-ocaml/nix-overlays/issues/1731)
- [x] merge changelog in `main` https://github.com/ocaml/dune/pull/11056
- [x] add an entry in ocaml.org `data/changelog/dune` https://github.com/ocaml/ocaml.org/pull/2798
- [x] make a post on discuss (https://discuss.ocaml.org/t/ann-dune-3-16/14889/2?u=maiste=
