### ISSUE TITLE
3.17.0 release tracking

### ISSUE THREAD

**Issue by ElectreAAS** [ocaml/dune#11143]
## pre-branch blockers

(none)

## known blockers

- [x] All 3.17 changelogs merged #11144
- [x] test mirage ([GitHub Worfkow](https://github.com/ocaml/dune/actions/runs/11957948268))
- [x] test nix-overlays https://github.com/nix-ocaml/nix-overlays/pull/1781
- [x] Wait for the CI of the opam-repository [alpha0 PR](https://github.com/ocaml/opam-repository/pull/26951)
## release

- [x] open then merge [opam-repository PR](https://github.com/ocaml/opam-repository/pull/26975) :tada:
- [x] triage
  - [x] Upstream the revert of #10892 into main (initial revert found at #11164)
- [x] update nix-overlays PR

## post-release

- [x] merge changelog #11180
- [x] ocaml.org changelog https://github.com/ocaml/ocaml.org/pull/2848
- [x] discuss post https://discuss.ocaml.org/t/ann-dune-3-17/15770
- [x] close tracking issue

**Comment by anmonteiro** [comment]
opened a new overlays check at https://github.com/nix-ocaml/nix-overlays/pull/1781 with the latest commit from main, d2ddc436b78f4da6e245593f0da2349ef0245d5a

**Comment by maiste** [comment]
I opened the [alpha0](https://github.com/ocaml/opam-repository/pull/26951) PR on opam.

**Comment by shonfeder** [comment]
Last time we learned that it would save time if we had a list of all the revdeps failures from the previous release. So we saved them here: https://github.com/ocaml/opam-repository/pull/26816#issuecomment-2454701201

Until we have this automated somehow, I suggest updating the release plan to include saving these results at the end of the process and then referring back to them when evaluating the opam ci results.

**Comment by maiste** [comment]
Indeed, good idea! How do you back up them? Do you just copy the CI page, or is there a way in the CI to download them?

**Comment by shonfeder** [comment]
I just did this the stupidest possible way last time, and manually copied from the CI page.

**Comment by maiste** [comment]
[3.17.0](https://github.com/ocaml/opam-repository/pull/26975) PR on opam is opened.

**Comment by maiste** [comment]
Everything is merged so I'm closing the issue.

**Comment by ElectreAAS** [comment]
Commenting here to note that I added a mention of #11175, as it's the PR that finally fixed the problem that necessitated a revert. Thanks all!
