### ISSUE TITLE
3.17.1 release tracking

### ISSUE THREAD

**Issue by maiste** [ocaml/dune#11215]
## Preparation

- need backport:
 - [x] https://github.com/ocaml/dune/pull/11176 
 - [x] https://github.com/ocaml/dune/pull/11179
 - [x] https://github.com/ocaml/dune/pull/11204#event-15652627575
 - [x] https://github.com/ocaml/dune/pull/11194
- backports:
  - https://github.com/ocaml/dune/pull/11189 
  - https://github.com/ocaml/dune/pull/11216
  - https://github.com/ocaml/dune/pull/11218

## Release

- [x] prepare https://github.com/ocaml/dune/pull/11221
- [x] release 3.17.1 on opam https://github.com/ocaml/opam-repository/pull/27137
- [x] triage

## Post-release

- [x] upgrade version in nix-overlay https://github.com/nix-ocaml/nix-overlays/pull/1836
- [x] merge changelog in `main` https://github.com/ocaml/dune/pull/11230
- [x] add an entry in ocaml.org `data/changelog/dune` https://github.com/ocaml/ocaml.org/pull/2874
- [x] make a post on discuss https://discuss.ocaml.org/t/ann-dune-3-17/15770/4?u=maiste

**Comment by nojb** [comment]
Also https://github.com/ocaml/dune/pull/11194 must be backported.

**Comment by maiste** [comment]
Can I let you take care of the backport for this PR too? I'll backport the regression fix on my side.

**Comment by maiste** [comment]
@anmonteiro what should I do to add it to the `nix-overlays` to test this new version?
