### ISSUE TITLE
3.9.1 release tracking

### ISSUE THREAD

**Issue by emillon** [ocaml/dune#8123]
- [x] have a good fix for #8083 (temporary list)
  - #8100
  - #8121 
  - #8122
- backports
  - [x] #8127
  - [x] #8125
  - [x] #8126
- [x] release https://github.com/ocaml/opam-repository/pull/24073
- [x] triage
- [x] changelog merged https://github.com/ocaml/dune/pull/8129
- [x] discuss https://discuss.ocaml.org/t/ann-dune-3-9-0/12530/3
- [x] ocaml.org https://github.com/ocaml/ocaml.org/pull/1386

**Comment by tmcgilchrist** [comment]
thank you @emillon
