### ISSUE TITLE
3.10.0 release tracking

### ISSUE THREAD

**Issue by emillon** [ocaml/dune#8133]
## alpha1 (tentative date: 2023-07-25)

- known blockers
  - #8129
  - #8159
  - #8243 
  - #8234 
  - #8272
  - #8308
- [x] release submitted https://github.com/ocaml/opam-repository/pull/24170
- [x] triage
- [x] go/no go for alpha2

## release

- [x] test mirage
- [x] release https://github.com/ocaml/opam-repository/pull/24185
- [x] triage

## post-release

- [x] release notes
- [x] ocaml.org changelog https://github.com/ocaml/ocaml.org/pull/1467
- [x] discuss post
- [x] close milestone

**Comment by Alizter** [comment]
Here is the nixpkgs PR:
- https://github.com/NixOS/nixpkgs/pull/246178
