### ISSUE TITLE
3.9.2 release tracking

### ISSUE THREAD

**Issue by emillon** [ocaml/dune#8266]
- need backport
  - [x] #8243
  - [x] #8234
- backports
  - #8269
  - #8270
- [x] release https://github.com/ocaml/opam-repository/pull/24158
- [x] triage
- [x] changelog merged #8272
- [x] discuss https://discuss.ocaml.org/t/ann-dune-3-9-0/12530/3
- [x] ocaml.org https://github.com/ocaml/ocaml.org/pull/1458
