### ISSUE TITLE
3.11.1 release tracking

### ISSUE THREAD

**Issue by emillon** [ocaml/dune#8810]
- need backports
  - [x] #8806
  - [x] #8849
 - backports
   - #8892
   - #8893
- [x] release https://github.com/ocaml/opam-repository/pull/24607
- [x] triage
- [x] changelog merged https://github.com/ocaml/dune/pull/8896
- [x] discuss https://github.com/ocaml/ocaml.org/pull/1627
- [x] ocaml.org

**Comment by Alizter** [comment]
Here is the nixpkgs PR:
- https://github.com/NixOS/nixpkgs/pull/259975
