### ISSUE TITLE
3.12.0 release tracking

### ISSUE THREAD

**Issue by emillon** [ocaml/dune#9137]
## known blockers

- [x] #9009
- [x] All 3.11 changelogs merged
- [x] #9176
- [x] #9187 
- [x] #9199
- [x] #9239
- [x] #9243
- [x] #9215

## alpha1 (2023-11-10)

- [x] release submitted https://github.com/ocaml/opam-repository/pull/24776
- [x] triage
- [x] go/no go for next alpha

## alpha2 (2023-11-16)

- [x] release submitted https://github.com/ocaml/opam-repository/pull/24805
- [x] triage
- [x] go/no go for next alpha

## alpha3 (2023-11-22)

- [x] release submitted https://github.com/ocaml/opam-repository/pull/24826
- [x] triage
- [x] go/no go for next alpha

## release

- [x] test mirage
- [x] compile changelog
- [x] release submitted https://github.com/ocaml/opam-repository/pull/24862
- [x] triage

## post-release

- [x] ocaml.org changelog https://github.com/ocaml/ocaml.org/pull/1813
- [x] discuss post
- [x] close milestone
- [x] update process with lang version check
- [x] update process with main branch checks

**Comment by Alizter** [comment]
I don't know if https://github.com/ocaml/dune/issues/9071 is worth adding to the list since it was broken in 3.11.

**Comment by emillon** [comment]
No, if that's not a regression it should not block the release.

**Comment by Alizter** [comment]
@emillon It appears to be a regression we missed in the last release however.

**Comment by emillon** [comment]
Sorry, I don't want to add more reasons to delay the release. If a fix is ready, no problem with including it, though.

**Comment by Alizter** [comment]
@emillon The dune lang version needs to be bumped to 3.12.

**Comment by emillon** [comment]
> @emillon The dune lang version needs to be bumped to 3.12.

Why is that? If nothing changes when `(lang dune 3.11)` is changed into `(lang dune 3.12)` I don't think there's a need to add this version.

**Comment by emillon** [comment]
In that case they have to declare that as a piece of metadata in the opam file. Adding an explicit bound on `dune` in `(package)` should work. Actually I would not advice changing a `(lang dune)` version for something that's not versioned against the language,

**Comment by Alizter** [comment]
@emillon If we version bump for 3.13 will we need to do two version or skip 3.12 entirely? I think its kind of surprising not to have 3.12.

**Comment by emillon** [comment]
I reckon it's a bit unusual. I tought there was a precedent but I can't find it so probably it didn't happen. But I don't think there's a concrete issue with not bumping the lang version if the lang is the same.

**Comment by emillon** [comment]
That's an interesting point, yes. That's why I don't think it's useful to recommend using the latest version (personally I advice starting at 3.0 and following error messages). But `dune init` is going to do the right thing and the error message is going to say the right thing so I think we can keep it that way for that release.
