### ISSUE TITLE
3.13.0 release tracking

### ISSUE THREAD

**Issue by emillon** [ocaml/dune#9695]
## known blockers

- [x] All 3.12 changelogs merged
- [x] broken revdeps fixed https://github.com/ocaml/opam-repository/pull/25078
- [x] test mirage
- [x] test nix-overlays https://github.com/nix-ocaml/nix-overlays/pull/1209

## Alpha1

- [x] release submitted https://github.com/ocaml/opam-repository/pull/25067
- [x] triage
- [x] go/no go

## release

- [x] changelog
- [x] release submitted https://github.com/ocaml/opam-repository/pull/25081
- [x] triage

## post-release

- [x] ocaml.org changelog https://github.com/ocaml/ocaml.org/pull/1976
  - [x] include modules (ask @nojb)
- [x] discuss post
- [x] close milestone
